### ISSUE TITLE
[Question] Config for forwarding home KNX network to development net 

### ISSUE THREAD

**Issue by DrAColian** [calimero-project/calimero-server#19]
Hey,

so I've a calimero-server up an running for a development KNX system in order to keep my home system "clean".

Now, I'm wondering, if you have any idea for a configuration so the signals from my home KNX net are routed to my development net, but not vice versa - so the development communication should stay in that net.

Thnaks in advanced and kind regard
Dr.A.Colian

**Comment by bmalinowsky** [comment]
I'm assuming you are solely talking about IP nets? The calimero server can filter KNX messages (like with the group address filter table), but then you wouldn't be able to observe them at all at the client side because they get blocked inside the server.

On Linux you would do this with _iptables_, e.g., when you know that all the dev communication comes from 192.168.x.y, you can add
`iptables -I INPUT -s 192.168.x.y -j DROP`, which throws away all messages from that sender address. One can refine those rules ad nauseam, but it's essentially that.
